import json
from datetime import datetime, timezone
from urllib.parse import quote

from app.models.schemas import (
    SEVERITY_LABELS,
    SEVERITY_ORDER,
    AuditMeta,
    AuditSummary,
    Finding,
    Severity,
)

DISCLAIMER = (
    "> **Disclaimer**: This report was generated by automated tools (Slither) with AI assistance. "
    "It is for reference only and does not constitute a formal security audit. "
    "Always perform manual review before mainnet deployment."
)


def _location_str(finding: Finding) -> str:
    if finding.file and finding.line:
        return f"{finding.file}:{finding.line}"
    if finding.file:
        return finding.file
    return "unknown"


def _is_collapsed_severity(finding: Finding) -> bool:
    return finding.severity in {Severity.INFORMATIONAL, Severity.OPTIMIZATION}


def _inline_text(value: str) -> str:
    return " ".join(value.replace("\r", " ").replace("\n", " ").split())


def build_summary(findings: list[Finding]) -> AuditSummary:
    summary = AuditSummary(total=len(findings))
    for f in findings:
        if f.severity.value == "High":
            summary.high += 1
        elif f.severity.value == "Medium":
            summary.medium += 1
        elif f.severity.value == "Low":
            summary.low += 1
        elif f.severity.value == "Informational":
            summary.informational += 1
        elif f.severity.value == "Optimization":
            summary.optimization += 1
        if f.ai.ai_success:
            summary.ai_explained += 1
    return summary


def _is_readiness_heuristic(finding: Finding) -> bool:
    return finding.source == "readiness-heuristic"


def _append_finding(lines: list[str], finding: Finding, heading_level: int = 3) -> None:
    label = SEVERITY_LABELS.get(finding.severity, finding.severity.value)
    title = finding.ai.title or finding.detector
    lines.append(f"{'#' * heading_level} [{label}] {title}")
    lines.append("")
    lines.append(f"- **Location**: {_location_str(finding)}")
    if finding.contract:
        lines.append(f"- **Contract**: `{finding.contract}`")
    if finding.function:
        lines.append(f"- **Function**: `{finding.function}`")

    if _is_readiness_heuristic(finding):
        lines.append(f"- **Readiness heuristic**: {finding.description}")
    else:
        lines.append(f"- **Slither finding**: {finding.description}")
    if finding.source_context:
        location = _location_str(finding)
        lines.append(f"- **Source context**: `{location}`")
        lines.append("")
        lines.append("```solidity")
        lines.append(finding.source_context)
        lines.append("```")
        lines.append("")

    if finding.ai_expanded and finding.ai.ai_success:
        if finding.ai.provider:
            lines.append(f"- **AI provider**: `{finding.ai.provider}`")
        lines.append(f"- **AI confidence**: `{finding.ai.confidence}`")
        lines.append(f"- **Assistive AI explanation**: {finding.ai.title or finding.detector}")
        lines.append(f"- **Problem**: {finding.ai.problem}")
        lines.append(f"- **Impact**: {finding.ai.impact}")
        lines.append(f"- **Recommendation**: {finding.ai.recommendation}")
        lines.append(
            f"- **Manual review required**: {'Yes' if finding.ai.manual_review_required else 'No'}"
        )
    elif not finding.ai_expanded:
        lines.append("- **Assistive AI explanation**: Not expanded (exceeds AI explanation limit)")
        lines.append("- **Manual review required**: Yes")
    else:
        if finding.ai.provider:
            lines.append(f"- **AI provider**: `{finding.ai.provider}`")
        if finding.ai.error:
            lines.append(f"- **Assistive AI explanation**: Unavailable ({_inline_text(finding.ai.error)})")
        else:
            lines.append("- **Assistive AI explanation**: Unavailable")
        lines.append("- **Manual review required**: Yes")

    if _is_readiness_heuristic(finding):
        lines.append(f"- **Heuristic detector**: `{finding.detector}`")
    else:
        lines.append(f"- **Slither detector**: `{finding.detector}`")
    lines.append("")


def _slither_findings(findings: list[Finding]) -> list[Finding]:
    return [finding for finding in findings if not _is_readiness_heuristic(finding)]


def generate_report(
    meta: AuditMeta,
    findings: list[Finding],
    slither_version: str = "unknown",
) -> str:
    findings = _slither_findings(findings)
    summary = meta.summary or build_summary(findings)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Solidity Security Triage Report",
        "",
        f"- **Project**: {meta.filename}",
        f"- **Task ID**: {meta.task_id}",
        f"- **Audit time**: {now}",
        f"- **Tool version**: Slither {slither_version}",
        f"- **Duration**: {meta.duration_sec:.1f}s" if meta.duration_sec else "",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| High | {summary.high} |",
        f"| Medium | {summary.medium} |",
        f"| Low | {summary.low} |",
        f"| Informational | {summary.informational} |",
        f"| Optimization | {summary.optimization} |",
        f"| **Total** | **{summary.total}** |",
        f"| AI explained | {summary.ai_explained} |",
        "",
        DISCLAIMER,
        "",
        "## Top risks",
        "",
    ]

    if not findings:
        lines.append("*No high-priority risks detected by Slither.*")
    else:
        top_risks = [f for f in findings if not _is_collapsed_severity(f)][:5]
        if top_risks:
            for finding in top_risks:
                lines.append(
                    f"- **{finding.severity.value}** `{finding.detector}` at `{_location_str(finding)}`: {finding.description}"
                )
        else:
            lines.append(
                "*No High, Medium, or Low findings. Informational and Optimization findings are folded below.*"
            )
    lines.append("")

    lines.extend(["## Findings", ""])

    if not findings:
        lines.append("*No security issues detected by Slither.*")
        lines.append("")
    else:
        primary_findings = [f for f in findings if not _is_collapsed_severity(f)]
        collapsed_findings = [f for f in findings if _is_collapsed_severity(f)]

        for finding in primary_findings:
            _append_finding(lines, finding)

        if collapsed_findings:
            lines.append("<details>")
            lines.append("<summary>Informational and Optimization findings</summary>")
            lines.append("")
            for finding in collapsed_findings:
                _append_finding(lines, finding)
            lines.append("</details>")
            lines.append("")

    lines.extend(
        [
            "## Appendix",
            "",
            f"Full Slither JSON: `GET /api/v1/audits/{meta.task_id}/slither`",
            f"SARIF results: `GET /api/v1/audits/{meta.task_id}/sarif`",
            "",
            "---",
            "*Generated by AISolidityAuditor*",
        ]
    )

    return "\n".join(line for line in lines if line is not None)


def _sarif_level(finding: Finding) -> str:
    if finding.severity == Severity.HIGH:
        return "error"
    if finding.severity == Severity.MEDIUM:
        return "warning"
    return "note"


def generate_sarif(
    findings: list[Finding],
    extra_tags: list[str] | None = None,
    *,
    readiness_tags: list[str] | None = None,
) -> dict:
    rules_by_id: dict[str, dict] = {}
    results: list[dict] = []
    glamsterdam_tags = readiness_tags if readiness_tags is not None else extra_tags or []

    for finding in sorted(findings, key=lambda f: (SEVERITY_ORDER.get(f.severity, 99), f.detector, f.id)):
        rule_id = finding.detector or "slither-finding"
        is_readiness = _is_readiness_heuristic(finding)
        if is_readiness:
            rule_tags = [
                "security",
                "readiness-heuristic",
                finding.severity.value.lower(),
                *glamsterdam_tags,
            ]
            rule_doc = {
                "id": rule_id,
                "name": rule_id,
                "shortDescription": {"text": rule_id},
                "fullDescription": {"text": f"Glamsterdam readiness heuristic: {rule_id}"},
                "helpUri": "https://github.com/PXLabs-code/AISolidityAuditor#esp-wishlist-alignment",
                "properties": {
                    "tool": "AISolidityAuditor-GlamsterdamReadiness",
                    "source": "readiness-heuristic",
                    "security-severity": {
                        Severity.HIGH: "8.0",
                        Severity.MEDIUM: "5.0",
                        Severity.LOW: "3.0",
                        Severity.INFORMATIONAL: "1.0",
                        Severity.OPTIMIZATION: "0.5",
                    }.get(finding.severity, "1.0"),
                    "tags": rule_tags,
                },
            }
        else:
            rule_tags = ["security", "slither", finding.severity.value.lower()]
            rule_doc = {
                "id": rule_id,
                "name": rule_id,
                "shortDescription": {"text": rule_id},
                "fullDescription": {"text": f"Slither detector: {rule_id}"},
                "helpUri": f"https://github.com/crytic/slither/wiki/Detector-Documentation#{quote(rule_id)}",
                "properties": {
                    "tool": "Slither",
                    "source": "slither",
                    "security-severity": {
                        Severity.HIGH: "8.0",
                        Severity.MEDIUM: "5.0",
                        Severity.LOW: "3.0",
                        Severity.INFORMATIONAL: "1.0",
                        Severity.OPTIMIZATION: "0.5",
                    }.get(finding.severity, "1.0"),
                    "tags": rule_tags,
                },
            }
        rules_by_id.setdefault(rule_id, rule_doc)
        properties = {
            "severity": finding.severity.value,
            "source": finding.source,
            "tool": "AISolidityAuditor-GlamsterdamReadiness" if is_readiness else "Slither",
            "rule_confidence": finding.rule_confidence,
            "related_eips": finding.related_eips or None,
            "contract": finding.contract,
            "function": finding.function,
            "ai_success": finding.ai.ai_success,
            "ai_provider": finding.ai.provider,
            "ai_error": finding.ai.error,
            "manual_review_required": finding.ai.manual_review_required,
            "ai_confidence": finding.ai.confidence,
            "source_start_line": finding.source_start_line,
            "source_end_line": finding.source_end_line,
        }
        results.append(
            {
                "ruleId": rule_id,
                "level": _sarif_level(finding),
                "message": {"text": finding.description or rule_id},
                "locations": [
                    {
                        "physicalLocation": {
                            "artifactLocation": {"uri": finding.file or "unknown"},
                            "region": {"startLine": finding.line or 1},
                        }
                    }
                ],
                "properties": {key: value for key, value in properties.items() if value is not None},
            }
        )

    return {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "AISolidityAuditor",
                        "informationUri": "https://github.com/PXLabs-code/AISolidityAuditor",
                        "rules": list(rules_by_id.values()),
                    }
                },
                "results": json.loads(json.dumps(results, default=str)),
            }
        ],
    }
