from datetime import datetime, timezone

from app.models.schemas import SEVERITY_LABELS, AuditMeta, AuditSummary, Finding

DISCLAIMER = (
    "> **Disclaimer**: This report was generated by automated tools (Slither) with AI assistance. "
    "It is for reference only and does not constitute a formal security audit. "
    "Always perform manual review before mainnet deployment."
)


def _location_str(finding: Finding) -> str:
    if finding.file and finding.line:
        return f"{finding.file}:{finding.line}"
    if finding.file:
        return finding.file
    return "unknown"


def build_summary(findings: list[Finding]) -> AuditSummary:
    summary = AuditSummary(total=len(findings))
    for f in findings:
        if f.severity.value == "High":
            summary.high += 1
        elif f.severity.value == "Medium":
            summary.medium += 1
        elif f.severity.value == "Low":
            summary.low += 1
        elif f.severity.value == "Informational":
            summary.informational += 1
        elif f.severity.value == "Optimization":
            summary.optimization += 1
        if f.ai.ai_success:
            summary.ai_explained += 1
    return summary


def generate_report(
    meta: AuditMeta,
    findings: list[Finding],
    slither_version: str = "unknown",
) -> str:
    summary = meta.summary or build_summary(findings)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        "# Smart Contract Audit Report",
        "",
        f"- **Project**: {meta.filename}",
        f"- **Task ID**: {meta.task_id}",
        f"- **Audit time**: {now}",
        f"- **Tool version**: Slither {slither_version}",
        f"- **Duration**: {meta.duration_sec:.1f}s" if meta.duration_sec else "",
        "",
        "## Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| High | {summary.high} |",
        f"| Medium | {summary.medium} |",
        f"| Low | {summary.low} |",
        f"| Informational | {summary.informational} |",
        f"| Optimization | {summary.optimization} |",
        f"| **Total** | **{summary.total}** |",
        f"| AI explained | {summary.ai_explained} |",
        "",
        DISCLAIMER,
        "",
        "## Findings",
        "",
    ]

    if not findings:
        lines.append("*No security issues detected by Slither.*")
        lines.append("")
    else:
        for finding in findings:
            label = SEVERITY_LABELS.get(finding.severity, finding.severity.value)
            title = finding.ai.title or finding.detector
            lines.append(f"### [{label}] {title}")
            lines.append("")
            lines.append(f"- **Location**: {_location_str(finding)}")
            if finding.contract:
                lines.append(f"- **Contract**: `{finding.contract}`")
            if finding.function:
                lines.append(f"- **Function**: `{finding.function}`")

            if finding.ai_expanded and finding.ai.ai_success:
                if finding.ai.provider:
                    lines.append(f"- **AI provider**: `{finding.ai.provider}`")
                lines.append(f"- **Problem**: {finding.ai.problem}")
                lines.append(f"- **Impact**: {finding.ai.impact}")
                lines.append(f"- **Recommendation**: {finding.ai.recommendation}")
            elif not finding.ai_expanded:
                lines.append("- **AI explanation**: Not expanded (exceeds AI explanation limit)")
                lines.append(f"- **Original description**: {finding.description}")
            else:
                if finding.ai.provider:
                    lines.append(f"- **AI provider**: `{finding.ai.provider}`")
                if finding.ai.error:
                    lines.append(f"- **AI explanation**: Unavailable ({finding.ai.error})")
                lines.append(f"- **Original description**: {finding.description}")

            lines.append(f"- **Slither detector**: `{finding.detector}`")
            lines.append("")

    lines.extend([
        "## Appendix",
        "",
        f"Full Slither JSON: `GET /api/v1/audits/{meta.task_id}/slither`",
        "",
        "---",
        "*Generated by AISolidityAuditor*",
    ])

    return "\n".join(line for line in lines if line is not None)
